<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LiteDB" Version="5.0.21" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SearchEngineAgentsConfiguration\SearchEngineAgentsConfiguration.csproj" />
    </ItemGroup>

    <Target Name="CopyConfigurationFiles" AfterTargets="Build">
        <ItemGroup>
            <ConfigFiles Include="$(MSBuildProjectDirectory)\..\SearchEngineAgentsConfiguration\appsettings*.json" />
        </ItemGroup>
        <Copy SourceFiles="@(ConfigFiles)" DestinationFolder="$(OutputPath)" OverwriteReadOnlyFiles="true" />
    </Target>

    <Target Name="CopyConfigurationFilesPublish" AfterTargets="Publish">
        <ItemGroup>
            <ConfigFilesPublish Include="$(MSBuildProjectDirectory)\..\SearchEngineAgentsConfiguration\appsettings*.json" />
        </ItemGroup>
        <Copy SourceFiles="@(ConfigFilesPublish)" DestinationFolder="$(PublishDir)" OverwriteReadOnlyFiles="true" />
    </Target>
</Project>
